include: package:lint/strict.yaml

linter:
  rules:
    always_use_package_imports: false # Tend to use relative imports locally and package imports when across features
    sort_unnamed_constructors_first: false # I prefer to have Class._() as the first one
    sort_pub_dependencies: false # I prefer to group the dependencies by functions rather than by name

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - 'test/.test_coverage.dart'
    - 'bin/cache/**'
    - 'lib/generated_plugin_registrant.dart'

  errors:
    # Ignore until open issue is resolved
    # https://github.com/rrousselGit/freezed/issues/488
    invalid_annotation_target: ignore
