name: paid_code_test
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Network
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.1

  # DI
  get_it: ^7.6.2
  provider: ^6.0.5

  # State Management
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5

  # Model
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  built_collection: ^5.1.1

  # Capabilities
  logging: ^1.2.0
  cached_network_image: ^3.2.3

  # Util
  collection: ^1.17.2
  intl: ^0.18.1

dev_dependencies:
  # Test
  flutter_test:
    sdk: flutter

  # Build runner and code generation
  build_runner: ^2.4.6
  freezed: ^2.4.1
  mobx_codegen: ^2.3.0
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8

  # Other
  lint: ^2.1.2

flutter:
  uses-material-design: true
